Update and rename 13.yml to ace5_pro.yml

diff --git a/.github/workflows/ace5_pro.yml b/.github/workflows/ace5_pro.yml
--- a/.github/workflows/ace5_pro.yml
+++ b/.github/workflows/ace5_pro.yml
@@ -165,16 +165,20 @@ jobs:
           cd kernel_platform
           mkdir out
           export PATH="/usr/lib/ccache:$PATH"
-          ./build_with_bazel.py \
-            -t pineapple \
-            gki \
-            --jobs=$(nproc --all) \
-            --verbose_failures \
-            --config=stamp \
-            --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom \
-            --ignore_missing_projects \
-            --lto=thin \
-            -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
+          if [ -f ./build_with_bazel.py ]; then
+            ./build_with_bazel.py \
+              -t ${{ inputs.soc }} \
+              gki \
+              --jobs=$(nproc --all) \
+              --verbose_failures \
+              --config=stamp \
+              --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom \
+              --ignore_missing_projects \
+              --lto=thin \
+              -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
+          else
+            ./kernel_platform/oplus/build/oplus_build_kernel.sh sun perf
+          fi
       - name: Create ZIP Package
         working-directory: builds/${{ env.ROOT_DIR }}
         run: |
@@ -195,7 +199,7 @@ jobs:
           }
           ls -lh "../$ZIP_NAME"
           echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV
-      
+          
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
